# Dependencies
markdown:         redcarpet
highlighter:	  pygments

# Permalinks
permalink:        pretty

# Setup
title:            arteeconomico/artinpocket
tagline:          Un blog d'artinpocket
description:      "arte economico, bloc d'<a href='http://www.artinpocket.cat' target='_blank'>artinpocket</a>. Creat per <a href='http://www.oxygen.cat/' target='_blank'>Oxygen.cat</a>."
url:              'https://www.arteeconomico.com'
icon:			  Artinpocket_Icon_Pocket.png
twitter:		  artinpocket

author:
  name:           'Artinpocket'
  url:            https://twitter.com/freecates

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/arteeconomico/arteeconomico.github.io

assets: 
  baseurl: /public/

bower_components: 
  baseurl: /bower_components/
